### ISSUE TITLE
Scrape full party name rather than the abbreviations

### ISSUE THREAD

**Issue by chrismytton** [mysociety/argentina-diputados-mendoza#3]
Currently the party names coming out of the scraper are the abbreviations, e.g. "UCR", "PJ" etc. 

Could we instead have the full party names, as they appear on [this page](http://www.hcdmza.gob.ar/web/institucional/bloques.html), e.g. "Unión Cívica Radical", "Partido Justicialista" etc?

**Comment by jacksonj04** [comment]
Fixed in https://github.com/mysociety/argentina-diputados-mendoza/commit/16fb55eea81d111dcad869d832f0e65d82e248b2
